package analysis_test

import (
	"bytes"
	"encoding/json"
	"errors"
	"math"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/kellen-miller/deburr/internal/analysis"
	"github.com/kellen-miller/deburr/internal/report"
)

func TestAnalyzeCountsBranchShortCircuitAndDefaultSwitch(t *testing.T) {
	root := t.TempDir()
	writeSource(t, root, "decisions.go", `package sample

func Decisions(value int) int {
	if value > 0 && value < 10 {
		return 1
	}
	switch value {
	default:
		return 0
	}
}
`)

	result := analyze(t, root)
	function := functionByName(t, result, "Decisions")

	if function.Cyclomatic != 3 {
		t.Fatalf("Decisions cyclomatic complexity = %d, want 3 (base + if + short-circuit)", function.Cyclomatic)
	}

	if function.MaxNesting != 1 {
		t.Fatalf("Decisions max nesting = %d, want 1", function.MaxNesting)
	}
}

func TestAnalyzeAccountsNestedClosureAndSkipsNoBodyDeclaration(t *testing.T) {
	root := t.TempDir()
	writeSource(t, root, "closures.go", `package sample

func Outer(value int) int {
	total := 0
	total += func() int {
		if value > 0 {
			return 1
		}
		return 2
	}()
	return total
}

func Declared()
`)

	result := analyze(t, root)
	outer := functionByName(t, result, "Outer")
	closure := functionByName(t, result, "Outer.func1")

	if outer.SLOC != 4 {
		t.Fatalf("Outer SLOC = %d, want 4 lines owned outside the closure", outer.SLOC)
	}

	if closure.SLOC != 6 {
		t.Fatalf("Outer.func1 SLOC = %d, want 6 closure lines", closure.SLOC)
	}

	if outer.SLOC+closure.SLOC != 10 {
		t.Fatalf("nested function SLOC = %d, want 10", outer.SLOC+closure.SLOC)
	}

	if len(result.Functions) != 2 {
		t.Fatalf("function count = %d, want only Outer and its closure", len(result.Functions))
	}
}

func TestAnalyzeCountsMultilineLiteralLinesInFunctionSLOC(t *testing.T) {
	root := t.TempDir()
	writeSource(t, root, "literal.go", `package sample

func Values() []int {
	values := []int{
		1,
		2,
	}
	return values
}
`)

	result := analyze(t, root)
	function := functionByName(t, result, "Values")

	if function.SLOC != 7 {
		t.Fatalf("Values SLOC = %d, want all 7 non-blank source lines", function.SLOC)
	}

	if result.Metrics.All.CodeLines != 8 {
		t.Fatalf("all code lines = %d, want 8", result.Metrics.All.CodeLines)
	}
}

func TestAnalyzeCountsCRLFMultilineLiteralLinesInFunctionSLOC(t *testing.T) {
	root := t.TempDir()
	writeSourceBytes(t, root, "crlf.go", crlfMultilineSource())

	result := analyze(t, root)
	function := functionByName(t, result, "Text")

	if function.SLOC != 24 {
		t.Fatalf("Text SLOC = %d, want all 24 non-blank source lines", function.SLOC)
	}
}

func TestAnalyzeUsesPhysicalPositionsForLineDirectives(t *testing.T) {
	root := t.TempDir()
	writeSource(t, root, "directive.go", `package sample

//line virtual.go:100
func Directive(value int) bool {
	if value > 0 {
		return true
	}
	return false
}
`)

	result := analyze(t, root)
	function := functionByName(t, result, "Directive")

	if function.Path != "directive.go" {
		t.Fatalf("directive function path = %q, want physical path directive.go", function.Path)
	}

	if function.Start.Line != 4 || function.End.Line != 9 {
		t.Fatalf("directive function lines = %d-%d, want physical lines 4-9", function.Start.Line, function.End.Line)
	}

	if function.SLOC != 6 {
		t.Fatalf("directive function SLOC = %d, want physical lines 4-9", function.SLOC)
	}
}

func TestAnalyzeRecognizesGeneratedMarkerAfterBlockLicense(t *testing.T) {
	root := t.TempDir()
	writeSource(t, root, "generated.go", `/*
Copyright 2026 Example
All rights reserved.
*/

// Code generated by example. DO NOT EDIT.

package sample

func Generated() {}
`)

	result := analyze(t, root)
	file := fileByPath(t, result, "generated.go")

	if file.Category != report.CategoryGenerated {
		t.Fatalf("generated file category = %q, want %q", file.Category, report.CategoryGenerated)
	}

	if file.Status != report.FileExcluded {
		t.Fatalf("generated file status = %q, want %q", file.Status, report.FileExcluded)
	}

	if result.Coverage.Excluded != 1 || result.Coverage.Analyzed != 0 {
		t.Fatalf(
			"generated coverage = analyzed %d, excluded %d; want analyzed 0, excluded 1",
			result.Coverage.Analyzed,
			result.Coverage.Excluded,
		)
	}
}

func TestAnalyzeCountsMalformedGoOnceAndReturnsError(t *testing.T) {
	root := t.TempDir()
	writeSource(t, root, "broken.go", `package sample

func Broken( {
`)

	result, err := analysis.Analyze(t.Context(), root, analysis.DefaultConfig())
	if err == nil {
		t.Fatal("Analyze returned nil error for malformed Go")
	}

	var analysisErr *analysis.AnalysisError
	if !errors.As(err, &analysisErr) {
		t.Fatalf("Analyze error type = %T, want *analysis.AnalysisError", err)
	}

	if len(analysisErr.Failures) != 1 {
		t.Fatalf("analysis failures = %d, want 1", len(analysisErr.Failures))
	}

	if result.Coverage.Discovered != 1 || result.Coverage.ParseErrors != 1 {
		t.Fatalf(
			"malformed coverage = discovered %d, parse errors %d; want 1 and 1",
			result.Coverage.Discovered,
			result.Coverage.ParseErrors,
		)
	}

	if len(result.Files) != 1 {
		t.Fatalf("reported files = %d, want 1", len(result.Files))
	}

	if result.Files[0].Status != report.FileParseError {
		t.Fatalf("malformed file status = %q, want %q", result.Files[0].Status, report.FileParseError)
	}
}

func TestAnalyzeCategoryTotalsMatchAllMetrics(t *testing.T) {
	root := t.TempDir()
	writeSource(t, root, "production.go", `package sample

func Production(value int) int {
	if value > 0 {
		return value
	}
	return 0
}
`)
	writeSource(t, root, "production_test.go", `package sample

func TestProduction() {}
`)
	writeSource(t, root, filepath.Join("testdata", "fixture.go"), `package fixture

func Fixture() {}
`)
	writeSource(t, root, filepath.Join("vendor", "dependency.go"), `package dependency

func Dependency() {}
`)
	writeSource(t, root, "notes.txt", "notes\n")

	result := analyze(t, root)
	assertCoverageTotals(t, result)

	all := result.Metrics.All
	production := result.Metrics.Production
	testMetrics := result.Metrics.Test
	if all.CodeLines != production.CodeLines+testMetrics.CodeLines {
		t.Fatalf(
			"all code lines = %d, production + test = %d",
			all.CodeLines,
			production.CodeLines+testMetrics.CodeLines,
		)
	}

	if all.Functions != production.Functions+testMetrics.Functions {
		t.Fatalf(
			"all functions = %d, production + test = %d",
			all.Functions,
			production.Functions+testMetrics.Functions,
		)
	}

	if all.Cyclomatic != production.Cyclomatic+testMetrics.Cyclomatic {
		t.Fatalf(
			"all cyclomatic = %d, production + test = %d",
			all.Cyclomatic,
			production.Cyclomatic+testMetrics.Cyclomatic,
		)
	}

	if !closeEnough(all.Mass, production.Mass+testMetrics.Mass) {
		t.Fatalf("all mass = %.12f, production + test = %.12f", all.Mass, production.Mass+testMetrics.Mass)
	}

	if all.HighComplexityFunctions != production.HighComplexityFunctions+testMetrics.HighComplexityFunctions {
		t.Fatalf(
			"all high-complexity functions = %d, production + test = %d",
			all.HighComplexityFunctions,
			production.HighComplexityFunctions+testMetrics.HighComplexityFunctions,
		)
	}

	if !closeEnough(all.HighComplexityMass, production.HighComplexityMass+testMetrics.HighComplexityMass) {
		t.Fatalf(
			"all high-complexity mass = %.12f, production + test = %.12f",
			all.HighComplexityMass,
			production.HighComplexityMass+testMetrics.HighComplexityMass,
		)
	}

	if all.MaxNesting != max(production.MaxNesting, testMetrics.MaxNesting) {
		t.Fatalf(
			"all max nesting = %d, production/test max = %d",
			all.MaxNesting,
			max(production.MaxNesting, testMetrics.MaxNesting),
		)
	}
}

func TestAnalyzeJSONIsDeterministicAcrossEquivalentRoots(t *testing.T) {
	left := t.TempDir()
	right := t.TempDir()
	for _, root := range []string{left, right} {
		writeSource(t, root, "main.go", `package sample

func Main(value int) int {
	if value > 0 && value < 10 {
		return value
	}
	return 0
}
`)
		writeSource(t, root, "main_test.go", `package sample

func TestMain() {}
`)
	}

	leftReport := analyze(t, left)
	rightReport := analyze(t, right)
	leftJSON, err := json.Marshal(leftReport)
	if err != nil {
		t.Fatalf("marshal left report: %v", err)
	}

	rightJSON, err := json.Marshal(rightReport)
	if err != nil {
		t.Fatalf("marshal right report: %v", err)
	}

	if !bytes.Equal(leftJSON, rightJSON) {
		t.Fatalf("equivalent roots produced different JSON reports:\nleft: %s\nright: %s", leftJSON, rightJSON)
	}
}

func TestAnalyzeNoGoInputReportsExplicitCoverage(t *testing.T) {
	root := t.TempDir()
	writeSource(t, root, "README.md", "documentation\n")

	result := analyze(t, root)
	if result.Coverage.Discovered != 1 || result.Coverage.Analyzed != 0 || result.Coverage.Unsupported != 1 {
		t.Fatalf(
			"no-Go coverage = discovered %d, analyzed %d, unsupported %d; want 1, 0, 1",
			result.Coverage.Discovered,
			result.Coverage.Analyzed,
			result.Coverage.Unsupported,
		)
	}

	if len(result.Files) != 1 || result.Files[0].Status != report.FileUnsupported {
		t.Fatalf("no-Go files = %#v, want one unsupported file", result.Files)
	}

	if result.Metrics.All.CodeLines != 0 || result.Metrics.All.Functions != 0 {
		t.Fatalf(
			"no-Go metrics = code lines %d, functions %d; want 0, 0",
			result.Metrics.All.CodeLines,
			result.Metrics.All.Functions,
		)
	}
}

func analyze(t *testing.T, root string) report.Report {
	t.Helper()
	result, err := analysis.Analyze(t.Context(), root, analysis.DefaultConfig())
	if err != nil {
		t.Fatalf("Analyze(%q): %v", root, err)
	}

	return result
}

func writeSource(t *testing.T, root, name, content string) {
	t.Helper()
	writeSourceBytes(t, root, name, []byte(content))
}

func writeSourceBytes(t *testing.T, root, name string, content []byte) {
	t.Helper()
	path := filepath.Join(root, name)
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		t.Fatalf("mkdir %q: %v", filepath.Dir(path), err)
	}

	if err := os.WriteFile(path, content, 0o644); err != nil {
		t.Fatalf("write %q: %v", path, err)
	}
}

func crlfMultilineSource() []byte {
	var source strings.Builder
	source.WriteString("package sample\r\n\r\nfunc Text() string {\r\n\ttext := `")
	for index := range 20 {
		source.WriteByte(byte('a' + index))
		source.WriteString("\r\n")
	}
	source.WriteString("`\r\n\treturn text\r\n}\r\n")
	return []byte(source.String())
}

func functionByName(t *testing.T, result report.Report, name string) report.Function {
	t.Helper()
	for index := range result.Functions {
		function := &result.Functions[index]
		if function.Name == name {
			return *function
		}
	}

	t.Fatalf("function %q not found in %#v", name, result.Functions)
	return report.Function{}
}

func fileByPath(t *testing.T, result report.Report, path string) report.File {
	t.Helper()
	for _, file := range result.Files {
		if file.Path == path {
			return file
		}
	}

	t.Fatalf("file %q not found in %#v", path, result.Files)
	return report.File{}
}

func assertCoverageTotals(t *testing.T, result report.Report) {
	t.Helper()
	var discovered, analyzed, excluded, unsupported, readErrors, parseErrors int
	for _, category := range result.Coverage.ByCategory {
		discovered += category.Discovered
		analyzed += category.Analyzed
		excluded += category.Excluded
		unsupported += category.Unsupported
		readErrors += category.ReadErrors
		parseErrors += category.ParseErrors
	}

	coverage := result.Coverage
	if discovered != coverage.Discovered || analyzed != coverage.Analyzed || excluded != coverage.Excluded ||
		unsupported != coverage.Unsupported ||
		readErrors != coverage.ReadErrors ||
		parseErrors != coverage.ParseErrors {
		t.Fatalf(
			"category coverage totals = discovered %d analyzed %d excluded %d unsupported %d read errors %d parse errors %d; report = %#v",
			discovered,
			analyzed,
			excluded,
			unsupported,
			readErrors,
			parseErrors,
			coverage,
		)
	}
}

func closeEnough(left, right float64) bool {
	return math.Abs(left-right) < 1e-12
}
